### ISSUE TITLE
Build failure while running the application

### ISSUE THREAD

**Issue by bhalahariharan** [Yeikel200/ir_sensor_plugin#1]
### FAILURE: Build failed with an exception.

I'm using the latest version of `ir_sensor_plugin`
```
ir_sensor_plugin: ^0.1.4
```
```
minSdkVersion 19
targetSdkVersion 28
```

<img width="1161" alt="Screenshot 2020-07-29 at 10 42 22 PM" src="https://user-images.githubusercontent.com/25824784/88831307-c7098b80-d1ec-11ea-8380-d890bebba25d.png">

I have also tried to run the example flutter application which is present in the repository. Unfortunately, the build is failed with the same exception.

**Comment by yeikel16** [comment]
Hello @bhalahariharan, you just have to create a folder in the android directory called `libs`, which contains the library of ` flutter.jar`, which is only used to compile the project. Already update the repository with it, you can `git pull` to update your local repository. Thanks for reporting it.

**Comment by bhalahariharan** [comment]
@Yeikel200 Thanks for your quick response. Could you please publish the package to [pub.dev](https://pub.dev) so that I will update the plugin in my flutter application and make use of it.

**Comment by yeikel16** [comment]
@bhalahariharan I already uploaded the update to pub.dev. Any problem can let me know.
