### ISSUE TITLE
It doesn't work on my redmi note 7

### ISSUE THREAD

**Issue by Al-06** [Yeikel200/ir_sensor_plugin#2]
Hi!
First of all, I don't know if I must ask you for the error but I have to ask someone. Perhaps it's my fault but I don't know.
Besides, I don't have experience doing mobile apps...
I have the error showed in the image
![ir](https://user-images.githubusercontent.com/60584317/92049831-cb950700-ed8b-11ea-9482-7df0741841b1.PNG)
I just changed the line commented before the exception so that I can send an hexadecimal value to my IR receptor when I push the button "Transmitt List Int". I tried this because it's the same error that happens when I use the "Transmitt Specific Code HEX".
The code was copied from the [flutter example documentation](https://pub.dev/packages/ir_sensor_plugin/example)

I hope you do not mind.
Thanks for your contribution.
Regards

**Comment by yeikel16** [comment]
Hello @Alvaro-MM, first of all thanks for using the plugin, second you don't have to apologize, we are all learning.
Your error lies in line 107, the value you pass is not correct for the use of the plugin, if you look at the value of the example variable it is a String that contains in turn a list of values ​​HEX, in your case you are only giving a HEX value.
You can use [this page](https://www.remotecentral.com) to obtain the codes you want to transmit are classified by brand.

**Comment by angga-buku** [comment]
Hi! Thanks for writing this plugin, I was confused with this HEX values, how can I get the String of values HEX from a simple HEX value, like "FF02FD"? Is there any reference that you can give us?

**Comment by yeikel16** [comment]
Thanks to you for using it, it depends on where this code comes from, does it belong to a specific device?
I suggest you look on [this page](http://www.remotecentral.com), here are almost all the codes in the format that the plugin uses, which is in a list of HEX passed as a string (without a comma) or a list of INTs.
Another way to obtain it is to reverse engineering with an Arduino to the button of the remote control you are using.

**Comment by angga-buku** [comment]
I see, okay thank you. Your library have been a big help for me, cheers!
