### ISSUE TITLE
IR Capture

### ISSUE THREAD

**Issue by ghost** [Yeikel200/ir_sensor_plugin#3]
i would like to receive ir signal from the remote into the app

like i have the p30 pro phone and it has an app that can record a ir signal from a tv remote and use it in the app

could you make so anyone can receive the signal into the app/plugin to use as a decoder?

**Comment by yeikel16** [comment]
At this moment the plugin only has the transmission action, if you can get the **HEX** code of the week captured by your phone if you can transmit it with this plugin. You can create a PR with your idea, they are always welcome
